// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CircleAvgRaster
Rcpp::List CircleAvgRaster(const arma::vec& raster_vals, int ncol_ras, int nrow_ras, double xmin, double ymax, double xres, double yres, const arma::vec& centers_x, const arma::vec& centers_y, const arma::vec& offsets_x, const arma::vec& offsets_y, int only_unique, int n_threads);
RcppExport SEXP _SpatialEffect2_CircleAvgRaster(SEXP raster_valsSEXP, SEXP ncol_rasSEXP, SEXP nrow_rasSEXP, SEXP xminSEXP, SEXP ymaxSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP centers_xSEXP, SEXP centers_ySEXP, SEXP offsets_xSEXP, SEXP offsets_ySEXP, SEXP only_uniqueSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type raster_vals(raster_valsSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_ras(ncol_rasSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_ras(nrow_rasSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type centers_x(centers_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type centers_y(centers_ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsets_x(offsets_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsets_y(offsets_ySEXP);
    Rcpp::traits::input_parameter< int >::type only_unique(only_uniqueSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(CircleAvgRaster(raster_vals, ncol_ras, nrow_ras, xmin, ymax, xres, yres, centers_x, centers_y, offsets_x, offsets_y, only_unique, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// CircleAvgFromPredictions
Rcpp::List CircleAvgFromPredictions(const arma::vec& predictions, const arma::ivec& group_ids, int nz);
RcppExport SEXP _SpatialEffect2_CircleAvgFromPredictions(SEXP predictionsSEXP, SEXP group_idsSEXP, SEXP nzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_ids(group_idsSEXP);
    Rcpp::traits::input_parameter< int >::type nz(nzSEXP);
    rcpp_result_gen = Rcpp::wrap(CircleAvgFromPredictions(predictions, group_ids, nz));
    return rcpp_result_gen;
END_RCPP
}
// ConleySE
Rcpp::List ConleySE(const arma::vec& res, const arma::mat& W_meat, const arma::mat& dist, const arma::mat& XXinv, double cutoff, int kernel, int trim, int if_edof, int n_threads);
RcppExport SEXP _SpatialEffect2_ConleySE(SEXP resSEXP, SEXP W_meatSEXP, SEXP distSEXP, SEXP XXinvSEXP, SEXP cutoffSEXP, SEXP kernelSEXP, SEXP trimSEXP, SEXP if_edofSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_meat(W_meatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XXinv(XXinvSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< int >::type if_edof(if_edofSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ConleySE(res, W_meat, dist, XXinv, cutoff, kernel, trim, if_edof, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// ConleySE2
Rcpp::List ConleySE2(const arma::vec& res, const arma::mat& W_meat, const arma::mat& dist_kernel, const arma::mat& XXinv, int if_edof, int n_threads);
RcppExport SEXP _SpatialEffect2_ConleySE2(SEXP resSEXP, SEXP W_meatSEXP, SEXP dist_kernelSEXP, SEXP XXinvSEXP, SEXP if_edofSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_meat(W_meatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dist_kernel(dist_kernelSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XXinv(XXinvSEXP);
    Rcpp::traits::input_parameter< int >::type if_edof(if_edofSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ConleySE2(res, W_meat, dist_kernel, XXinv, if_edof, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// DistMatEuclidean
arma::mat DistMatEuclidean(const arma::vec& x, const arma::vec& y, int n_threads);
RcppExport SEXP _SpatialEffect2_DistMatEuclidean(SEXP xSEXP, SEXP ySEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(DistMatEuclidean(x, y, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// DistMatEuclidean2
arma::mat DistMatEuclidean2(const arma::vec& x1, const arma::vec& y1, const arma::vec& x2, const arma::vec& y2, int n_threads);
RcppExport SEXP _SpatialEffect2_DistMatEuclidean2(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y2(y2SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(DistMatEuclidean2(x1, y1, x2, y2, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// KernelMatrix
arma::mat KernelMatrix(const arma::mat& dist, double cutoff, int kernel, int trim, int n_threads);
RcppExport SEXP _SpatialEffect2_KernelMatrix(SEXP distSEXP, SEXP cutoffSEXP, SEXP kernelSEXP, SEXP trimSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< int >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(KernelMatrix(dist, cutoff, kernel, trim, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpatialEffect2_CircleAvgRaster", (DL_FUNC) &_SpatialEffect2_CircleAvgRaster, 13},
    {"_SpatialEffect2_CircleAvgFromPredictions", (DL_FUNC) &_SpatialEffect2_CircleAvgFromPredictions, 3},
    {"_SpatialEffect2_ConleySE", (DL_FUNC) &_SpatialEffect2_ConleySE, 9},
    {"_SpatialEffect2_ConleySE2", (DL_FUNC) &_SpatialEffect2_ConleySE2, 6},
    {"_SpatialEffect2_DistMatEuclidean", (DL_FUNC) &_SpatialEffect2_DistMatEuclidean, 3},
    {"_SpatialEffect2_DistMatEuclidean2", (DL_FUNC) &_SpatialEffect2_DistMatEuclidean2, 5},
    {"_SpatialEffect2_KernelMatrix", (DL_FUNC) &_SpatialEffect2_KernelMatrix, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpatialEffect2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
