# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CircleAvgRaster <- function(raster_vals, ncol_ras, nrow_ras, xmin, ymax, xres, yres, centers_x, centers_y, offsets_x, offsets_y, only_unique, n_threads) {
    .Call(`_SpatialEffect2_CircleAvgRaster`, raster_vals, ncol_ras, nrow_ras, xmin, ymax, xres, yres, centers_x, centers_y, offsets_x, offsets_y, only_unique, n_threads)
}

CircleAvgFromPredictions <- function(predictions, group_ids, nz) {
    .Call(`_SpatialEffect2_CircleAvgFromPredictions`, predictions, group_ids, nz)
}

ConleySE <- function(res, W_meat, dist, XXinv, cutoff, kernel, trim, if_edof, n_threads = 1L) {
    .Call(`_SpatialEffect2_ConleySE`, res, W_meat, dist, XXinv, cutoff, kernel, trim, if_edof, n_threads)
}

ConleySE2 <- function(res, W_meat, dist_kernel, XXinv, if_edof, n_threads = 1L) {
    .Call(`_SpatialEffect2_ConleySE2`, res, W_meat, dist_kernel, XXinv, if_edof, n_threads)
}

DistMatEuclidean <- function(x, y, n_threads = 1L) {
    .Call(`_SpatialEffect2_DistMatEuclidean`, x, y, n_threads)
}

DistMatEuclidean2 <- function(x1, y1, x2, y2, n_threads = 1L) {
    .Call(`_SpatialEffect2_DistMatEuclidean2`, x1, y1, x2, y2, n_threads)
}

KernelMatrix <- function(dist, cutoff, kernel = 1L, trim = 0L, n_threads = 1L) {
    .Call(`_SpatialEffect2_KernelMatrix`, dist, cutoff, kernel, trim, n_threads)
}

