# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ConleySE <- function(res, W_meat, dist, XXinv, cutoff, kernel, trim, if_edof) {
    .Call(`_SpatialEffect_ConleySE`, res, W_meat, dist, XXinv, cutoff, kernel, trim, if_edof)
}

ConleySE2 <- function(res, W_meat, dist_kernel, XXinv, kernel, trim, if_edof) {
    .Call(`_SpatialEffect_ConleySE2`, res, W_meat, dist_kernel, XXinv, kernel, trim, if_edof)
}

ConleySE_kernel <- function(dist, N, cutoff, kernel, trim) {
    .Call(`_SpatialEffect_ConleySE_kernel`, dist, N, cutoff, kernel, trim)
}

DistanceCalculation <- function(x_coord, y_coord, metric) {
    .Call(`_SpatialEffect_DistanceCalculation`, x_coord, y_coord, metric)
}

DistanceCalculation2 <- function(x_coord, y_coord, x_coord2, y_coord2, metric) {
    .Call(`_SpatialEffect_DistanceCalculation2`, x_coord, y_coord, x_coord2, y_coord2, metric)
}

calculate_tau <- function(Y, Zdata) {
    .Call(`_SpatialEffect_calculate_tau`, Y, Zdata)
}

effect_interactive <- function(Y0, dist, Zdata, Zneighbor, alpha, effect, sh, sc, a) {
    .Call(`_SpatialEffect_effect_interactive`, Y0, dist, Zdata, Zneighbor, alpha, effect, sh, sc, a)
}

nonmonoeffect_c <- function(d, sh, sc, a) {
    .Call(`_SpatialEffect_nonmonoeffect_c`, d, sh, sc, a)
}

effect_nonmo1 <- function(Y0, dist, Zdata, alpha, effect, sh, sc, a) {
    .Call(`_SpatialEffect_effect_nonmo1`, Y0, dist, Zdata, alpha, effect, sh, sc, a)
}

